name: 3mco
favicon: null
layout_spectrum: 0.30711
typography_spectrum: 0.24384
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f5f5f5'
    - '#000000'
    - '#ee1c25'
    - '#f5b5a5'
    - '#d4734a'
  brandStrength: 0.9375
  lightness: 0.5018754058983177
  saturation: 0.875
  rhythmicContrast: 0.8870652981568128
purpose: []
